controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
filterStadiumForm :
    path: /filterStadiumForm
    controller: App\Controller\HomeController::FilterFormSubmission
